# Generated by Django 3.2.7 on 2021-09-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyuploaded',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
