# Generated by Django 3.2.7 on 2021-09-27 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(choices=[('CIB', 'CIB'), ('HSBC', 'HSBC'), ('QNB', 'QNB')], default='CIB', max_length=9)),
                ('branch_number', models.CharField(max_length=100, unique=True, verbose_name='Branch_name')),
                ('account_number', models.CharField(max_length=100, unique=True, verbose_name='Account_number')),
                ('account_holder_name', models.CharField(max_length=100, unique=True, verbose_name='Account_holder_name')),
                ('name_ref', models.CharField(max_length=100, unique=True, verbose_name='Bank_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
