# Generated by Django 3.2.7 on 2021-09-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='bank_name',
        ),
    ]
