# Generated by Django 3.2.7 on 2021-09-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(choices=[('CIB', 'CIB'), ('SO', 'SO'), ('QNB', 'QNB')], default='CIB', max_length=9),
        ),
    ]
