# Generated by Django 3.2.7 on 2021-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='branch_number',
            field=models.CharField(max_length=100, verbose_name='Branch_name'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name_ref',
            field=models.CharField(max_length=100, verbose_name='Bank_name'),
        ),
    ]
