# Generated by Django 3.2.7 on 2021-09-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_bank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_holder_name',
            field=models.CharField(max_length=100, verbose_name='Account_holder_name'),
        ),
    ]
