# Generated by Django 3.2.7 on 2021-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_bank_account_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(choices=[('CIB', 'CIB'), ('HSBC', 'HSBC'), ('QNB', 'QNB')], default='CIB', max_length=9),
        ),
    ]
