# Generated by Django 3.2.7 on 2021-09-24 17:58

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210924_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EGP', max_digits=10, null=True),
        ),
    ]
