name: main

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - name: build the application
        run: |
          ls
          ls requirements.dev.txt
          docker-compose up
          docker-compose up --detach django postgres

      # - name: Sleep for 30 seconds
      #   run: sleep 30s
      #   shell: bash

      # - name: run test cases
      #   run: |
      #     docker-compose run django python3 manage.py test
