name: main

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: build the application
        run: |
          docker-compose up
          docker-compose up --detach django postgres

      # - name: Sleep for 30 seconds
      #   run: sleep 30s
      #   shell: bash

      # - name: run test cases
      #   run: |
      #     docker-compose run django python3 manage.py test
